Hashmap implementation
jabacat/jccc pull request #46
Opened 2024-06-26 20:29 UTC by NicoBliss

should close issue #15

2024-06-27 01:15 UTC, adamhutchings requested changes
Two small-ish things:
For consistency, could we name the structs `HashNode` and `HashMap`
And could you add a test file for this?

But aside from that, looks good!

2024-07-08 20:20 UTC, NicoBliss commented
> Two small-ish things: For consistency, could we name the structs `HashNode` and `HashMap` And could you add a test file for this?
> 
> But aside from that, looks good!

All of this has been added (and a bunch of files header's lightly modified... sorry about that)

2024-07-11 18:24 UTC, JakeRoggenbuck commented
I get an error when building.
```
.../jccc/src/util/test_hash.c: In function ‘test_hashing’:
.../jccc/src/util/test_hash.c:25:24: error: initialization of ‘const char *’ from incompatible pointer type ‘char (*)[6]’ [-Wincompatible-pointer-types]
   25 |     const char *key1 = &string1;
      |                        ^
.../jccc/src/util/test_hash.c:26:24: error: initialization of ‘const char *’ from incompatible pointer type ‘char (*)[6]’ [-Wincompatible-pointer-types]
   26 |     const char *key2 = &string2;
      |                        ^
```

2024-07-11 18:37 UTC, JakeRoggenbuck commented on src/util/test_hash.c
> +    tassert(hm_lookup(table, key) == (void *)128);
You may also want to change this to something like
```c
    tassert(*(int*)hm_lookup(table, key) == 128);
```

2024-07-11 18:40 UTC, JakeRoggenbuck commented
When I added `test_minimal_case();` to test_hash

```c
--- a/src/util/test_hash.c
+++ b/src/util/test_hash.c
@@ -10,6 +10,7 @@ int test_hash() {

     test_hashing();
     test_init_and_free();
+       test_minimal_case();
     test_100_inserts();
     test_100_removes();
```

When it's run, it segfaults,
```c
Running "test_hashing"
Running "test_init_and_free"
Running "test_minimal_case"
Warning: jccc: hashmap full!
Segmentation fault (core dumped)
```

2024-08-05 22:54 UTC, adamhutchings commented
Closing due to inactivity.

2024-08-05 22:54 UTC, closed without merging